<a href="https://colab.research.google.com/github/Siri11220816/EventSphere/blob/main/MySELAgent_01_Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("MySELAgent - Data Preprocessing")
print("Project started successfully!")

MySELAgent - Data Preprocessing
Project started successfully!

In [2]:
import os

folders = [
    "data/raw",
    "data/processed",
    "data/knowledge_base",
    "data/emotion"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Folders created successfully!")

Folders created successfully!

In [3]:
for root, dirs, files in os.walk("data"):
    print(root)

data
data/emotion
data/processed
data/knowledge_base
data/raw

In [4]:
import requests

url = "https://files.casel.org/CASEL-SEL-Framework-11.2020.pdf"

response = requests.get(url)

with open("data/raw/CASEL_SEL_Framework_2020.pdf", "wb") as f:
    f.write(response.content)

print("CASEL framework downloaded successfully!")

CASEL framework downloaded successfully!

In [5]:
import os

file_path = "data/raw/CASEL_SEL_Framework_2020.pdf"

if os.path.exists(file_path):
    print("File found!")
    print("File size:", os.path.getsize(file_path), "bytes")
else:
    print("File not found!")

File found!
File size: 688009 bytes

In [7]:
!pip install pypdf

Collecting pypdf
  Downloading pypdf-6.19.0-py3-none-any.whl.metadata (7.5 kB)
Downloading pypdf-6.19.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.5/395.5 kB 7.6 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.19.0

In [8]:
from pypdf import PdfReader

pdf_path = "data/raw/CASEL_SEL_Framework_2020.pdf"

reader = PdfReader(pdf_path)

print("Number of pages:", len(reader.pages))

text = ""

for page in reader.pages:
    text += page.extract_text() + "\n"

print("PDF text extracted successfully!")
print("Characters extracted:", len(text))

Number of pages: 4
PDF text extracted successfully!
Characters extracted: 11978

In [9]:
text_file = "data/raw/CASEL_SEL_Framework_2020.txt"

with open(text_file, "w", encoding="utf-8") as f:
    f.write(text)

print("Text file saved successfully!")
print(text_file)

Text file saved successfully!
data/raw/CASEL_SEL_Framework_2020.txt

In [10]:
print(text[:5000])

Social and emotional learning (SEL) is
an integral part of education and human
development. SEL is the process through
which all young people and adults acquire
and apply the knowledge, skills, and
attitudes to develop healthy identities,
manage emotions and achieve personal
and collective goals, feel and show
empathy for others, establish and
maintain supportive relationships, and
make responsible and caring decisions.
SEL advances educational equity and
excellence through authentic school-
family-community partnerships to
establish learning environments and
experiences that feature trusting and
collaborative relationships, rigorous and
meaningful curriculum and instruction,
and ongoing evaluation. SEL can help
address various forms of inequity and
empower young people and adults to
co-create thriving schools and contribute
to safe, healthy, and just communities.
CASEL ’S SEL FRAMEWORK:
What Are the Core Competence Areas
and Where Are They Promoted?
Learn more: www.casel.org/what-is-SEL

The CASEL 5
addresses five
broad, interrelated
areas of
competence and
examples for each:
self-awareness,
self-management,
social awareness,
relationship skills,
and responsible
decision-making. The
CASEL 5 can be
taught and applied
at various develop-
mental stages from
childhood to adult-
hood and across
diverse cultural
contexts to articu-
late what students
should know and
be able to do for
academic success,
school and civic en-
gagement, health
and wellness, and
fulfilling careers.
THE CASEL 5:
SELF-AWARENESS: The abilities to understand one’s own
emotions, thoughts, and values and how they influence
behavior across contexts. This includes capacities to
recognize one’s strengths and limitations with a well-
grounded sense of confidence and purpose. Such as:
• Int egrating personal and social identities
• Identifying per
sonal, cultural, and linguistic assets
• Identifying one’
s emotions
• Demons
trating honesty and integrity
• Linking f
eelings, values, and thoughts
• Examining pr
ejudices and biases
• Experiencing self-effic
acy
• Having a gr
owth mindset
• De
veloping interests and a sense of purpose
SELF-MANAGEMENT: The abilities to manage one’s emo-
tions, thoughts, and behaviors effectively in different situ-
ations and to achieve goals and aspirations. This includes
the capacities to delay gratification, manage stress, and
feel motivation & agency to accomplish personal/collective
goals. Such as:
• Managing one’ s emotions
• Identifying and using s
tress-management strategies
• Exhibiting self-discipline and self-motiv
ation
• Setting per
sonal and collective goals
• Using planning and or
ganizational skills
• Sho
wing the courage to take initiative
• Demons
trating personal and collective agency
SOCIAL AWARENESS: The abilities to understand the
perspectives of and empathize with others, including
those from diverse backgrounds, cultures, & contexts.
This includes the capacities to feel compassion for others,
understand broader historical and social norms for behav-
ior in different settings, and recognize family, school, and
community resources and supports. Such as:
• T aking others’ perspectives
• Rec
ognizing strengths in others
• Demons
trating empathy and compassion
• Sho
wing concern for the feelings of others
• Under
standing and expressing gratitude
• Identifying div
erse social norms, including unjust ones
• Rec
ognizing situational demands and opportunities
• Under
standing the influences of organizations/systems
on behavior
RELATIONSHIP SKILLS: The abilities to establish and main-
tain healthy and supportive relationships and to effectively
navigate settings with diverse individuals and groups.This
includes the capacities to communicate clearly, listen ac-
tively, cooperate, work collaboratively to problem solve and
negotiate conflict constructively, navigate settings with dif-
fering social and cultural demands and opportunities, provide
leadership, and seek or offer help when needed. Such as:
• Communic ating effectively
• De
veloping positive relationships
• Demons
trating cultural competency
• Pr
acticing teamwork and collaborative problem-solving
• Resol
ving conflicts constructively
• Resis
ting negative social pressure
• Sho
wing leadership in groups
• Seeking or off
ering support and help when needed
• St
anding up for the rights of others
RESPONSIBLE DECISION-MAKING: The abilities to make caring and constructive choices about personal behavior and
social interactions across diverse situations. This includes the capacities to consider ethical standards and safety con-
cerns, and to evaluate the benefits and consequences of various actions for personal, social, and collective well-being.
Such as:
www.casel.org/what-is-SEL
• Demons trating curiosity and open-mindedness
• Identifying solutions f
or personal and social problems
• Learning t
o make a reasoned judgment after
analyzing information, data, facts
• Anticipating and e
valuat

In [11]:
import pandas as pd

sel_data = [
    {
        "competency": "Self-Awareness",
        "description": "Understanding one's own emotions, thoughts, values, strengths, and limitations.",
        "skill": "Identifying emotions"
    },
    {
        "competency": "Self-Awareness",
        "description": "Understanding one's own emotions, thoughts, values, strengths, and limitations.",
        "skill": "Recognizing strengths and limitations"
    },
    {
        "competency": "Self-Awareness",
        "description": "Understanding one's own emotions, thoughts, values, strengths, and limitations.",
        "skill": "Developing interests and sense of purpose"
    },
    {
        "competency": "Self-Management",
        "description": "Managing emotions, thoughts, and behaviors effectively to achieve goals.",
        "skill": "Managing emotions"
    },
    {
        "competency": "Self-Management",
        "description": "Managing emotions, thoughts, and behaviors effectively to achieve goals.",
        "skill": "Managing stress"
    },
    {
        "competency": "Self-Management",
        "description": "Managing emotions, thoughts, and behaviors effectively to achieve goals.",
        "skill": "Setting personal and collective goals"
    },
    {
        "competency": "Social Awareness",
        "description": "Understanding others' perspectives and showing empathy toward people from diverse backgrounds.",
        "skill": "Taking others' perspectives"
    },
    {
        "competency": "Social Awareness",
        "description": "Understanding others' perspectives and showing empathy toward people from diverse backgrounds.",
        "skill": "Demonstrating empathy and compassion"
    },
    {
        "competency": "Social Awareness",
        "description": "Understanding others' perspectives and showing empathy toward people from diverse backgrounds.",
        "skill": "Showing concern for others' feelings"
    },
    {
        "competency": "Relationship Skills",
        "description": "Establishing and maintaining healthy relationships and working effectively with others.",
        "skill": "Communicating effectively"
    },
    {
        "competency": "Relationship Skills",
        "description": "Establishing and maintaining healthy relationships and working effectively with others.",
        "skill": "Teamwork and collaborative problem-solving"
    },
    {
        "competency": "Relationship Skills",
        "description": "Establishing and maintaining healthy relationships and working effectively with others.",
        "skill": "Resolving conflicts constructively"
    },
    {
        "competency": "Responsible Decision-Making",
        "description": "Making caring and constructive choices about personal behavior and social interactions.",
        "skill": "Identifying solutions to problems"
    },
    {
        "competency": "Responsible Decision-Making",
        "description": "Making caring and constructive choices about personal behavior and social interactions.",
        "skill": "Analyzing information and facts"
    },
    {
        "competency": "Responsible Decision-Making",
        "description": "Making caring and constructive choices about personal behavior and social interactions.",
        "skill": "Evaluating consequences of actions"
    }
]

df = pd.DataFrame(sel_data)

print("SEL dataset created!")
print("Number of records:", len(df))

df.head()

SEL dataset created!
Number of records: 15

,competency,description,skill
0,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Identifying emotions
1,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Recognizing strengths and limitations
2,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Developing interests and sense of purpose
3,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing emotions
4,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing stress

In [12]:
output_path = "data/processed/sel_concepts.csv"

df.to_csv(output_path, index=False)

print("SEL dataset saved successfully!")
print(output_path)

SEL dataset saved successfully!
data/processed/sel_concepts.csv

In [13]:
import pandas as pd

file_path = "data/processed/sel_concepts.csv"

check_df = pd.read_csv(file_path)

print("CSV loaded successfully!")
print("Rows:", len(check_df))
print("Columns:", list(check_df.columns))

check_df.head()

CSV loaded successfully!
Rows: 15
Columns: ['competency', 'description', 'skill']

,competency,description,skill
0,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Identifying emotions
1,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Recognizing strengths and limitations
2,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Developing interests and sense of purpose
3,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing emotions
4,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing stress

In [14]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://pg.casel.org/review-programs/"

response = requests.get(
    url,
    headers={"User-Agent": "Mozilla/5.0"},
    timeout=30
)

print("Website status:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

programs = []

# Find links that point to individual CASEL program pages
program_links = soup.select('a[href^="https://pg.casel.org/"]')

seen = set()

for link in program_links:
    name = link.get_text(" ", strip=True)
    href = link.get("href", "").strip()

    # Keep only likely program-detail pages
    if (
        name
        and href
        and href != url
        and href.rstrip("/") != "https://pg.casel.org"
        and name not in seen
        and name not in [
            "View Full Details",
            "Visit CASEL.org",
            "Program Guide",
            "View the program list",
            "Explore all SEL programs"
        ]
    ):
        # Avoid navigation/filter links
        if "/review-programs/" not in href and "/connect-your-criteria" not in href:
            seen.add(name)
            programs.append({
                "program_name": name,
                "program_url": href
            })

# Remove obvious duplicates
program_df = pd.DataFrame(programs).drop_duplicates(
    subset=["program_name"]
).reset_index(drop=True)

# Save the collected program information
output_path = "data/raw/casel_programs.csv"

program_df.to_csv(output_path, index=False)

print("Collection attempt completed!")
print("Programs collected:", len(program_df))
print("Saved to:", output_path)

program_df.head(10)

Website status: 200
Collection attempt completed!
Programs collected: 105
Saved to: data/raw/casel_programs.csv

,program_name,program_url
0,Forgot your password?,https://pg.casel.org/wp-login.php?action=lostp...
1,Identify Your Goals,https://pg.casel.org/identify-your-goals/
2,Compare Programs,https://pg.casel.org/compare-programs/
3,About the Program Guide,https://pg.casel.org/about-the-program-guide/
4,FAQs,https://pg.casel.org/faqs/
5,For Providers,https://pg.casel.org/for-providers/
6,.b,https://pg.casel.org/b/
7,4Rs,https://pg.casel.org/4rs/
8,Adventures Aboard the S.S. Grin,https://pg.casel.org/adventures-aboard-the-s-s...
9,Al’s Pals,https://pg.casel.org/als-pals/

In [15]:
import pandas as pd

input_path = "data/raw/casel_programs.csv"
output_path = "data/processed/casel_programs_clean.csv"

program_df = pd.read_csv(input_path)

# Website/navigation pages that are not SEL programs
remove_names = [
    "Forgot your password?",
    "Identify Your Goals",
    "Compare Programs",
    "About the Program Guide",
    "FAQs",
    "For Providers",
    "Program Guide",
    "Visit CASEL.org"
]

clean_df = program_df[
    ~program_df["program_name"].isin(remove_names)
].copy()

# Remove the generic ".b" page
clean_df = clean_df[
    clean_df["program_name"].str.strip() != ".b"
]

# Remove duplicate program names
clean_df = clean_df.drop_duplicates(
    subset=["program_name"]
).reset_index(drop=True)

# Save cleaned dataset
clean_df.to_csv(output_path, index=False)

print("Cleaning completed!")
print("Original rows:", len(program_df))
print("Clean rows:", len(clean_df))
print("Saved to:", output_path)

print("\nFirst 10 programs:")
display(clean_df.head(10))

Cleaning completed!
Original rows: 105
Clean rows: 98
Saved to: data/processed/casel_programs_clean.csv

First 10 programs:

,program_name,program_url
0,4Rs,https://pg.casel.org/4rs/
1,Adventures Aboard the S.S. Grin,https://pg.casel.org/adventures-aboard-the-s-s...
2,Al’s Pals,https://pg.casel.org/als-pals/
3,BASE Education,https://pg.casel.org/base-education/
4,Better Together Cubed,https://pg.casel.org/better-together-cubed/
5,"Building Assets, Reducing Risks (BARR)",https://pg.casel.org/building-assets-reducing-...
6,Captain McFinn: Explore Kindness,https://pg.casel.org/captain-mcfinn-explore-ki...
7,Caring School Community,https://pg.casel.org/caring-school-community/
8,Changemakers: A Social Emotional Learning Curr...,https://pg.casel.org/changemakers-a-social-emo...
9,CHARACTERplus Way,https://pg.casel.org/characterplus-way/

In [16]:
import pandas as pd

# Load our SEL dataset
df = pd.read_csv("data/processed/sel_concepts.csv")

# Remove missing values
df = df.dropna()

# Clean text
df["competency"] = df["competency"].str.strip()
df["description"] = df["description"].str.strip()
df["skill"] = df["skill"].str.strip()

# Remove duplicate records
df = df.drop_duplicates()

# Create a searchable text field
df["knowledge_text"] = (
    df["competency"] + ". " +
    df["description"] + " Skill: " +
    df["skill"]
)

# Save preprocessed dataset
output_path = "data/processed/sel_concepts_preprocessed.csv"
df.to_csv(output_path, index=False)

print("Preprocessing completed!")
print("Rows:", len(df))
print("Columns:", list(df.columns))
print("Saved to:", output_path)

display(df)

Preprocessing completed!
Rows: 15
Columns: ['competency', 'description', 'skill', 'knowledge_text']
Saved to: data/processed/sel_concepts_preprocessed.csv

,competency,description,skill,knowledge_text
0,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Identifying emotions,Self-Awareness. Understanding one's own emotio...
1,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Recognizing strengths and limitations,Self-Awareness. Understanding one's own emotio...
2,Self-Awareness,"Understanding one's own emotions, thoughts, va...",Developing interests and sense of purpose,Self-Awareness. Understanding one's own emotio...
3,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing emotions,"Self-Management. Managing emotions, thoughts, ..."
4,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Managing stress,"Self-Management. Managing emotions, thoughts, ..."
5,Self-Management,"Managing emotions, thoughts, and behaviors eff...",Setting personal and collective goals,"Self-Management. Managing emotions, thoughts, ..."
6,Social Awareness,Understanding others' perspectives and showing...,Taking others' perspectives,Social Awareness. Understanding others' perspe...
7,Social Awareness,Understanding others' perspectives and showing...,Demonstrating empathy and compassion,Social Awareness. Understanding others' perspe...
8,Social Awareness,Understanding others' perspectives and showing...,Showing concern for others' feelings,Social Awareness. Understanding others' perspe...
9,Relationship Skills,Establishing and maintaining healthy relations...,Communicating effectively,Relationship Skills. Establishing and maintain...
10,Relationship Skills,Establishing and maintaining healthy relations...,Teamwork and collaborative problem-solving,Relationship Skills. Establishing and maintain...
11,Relationship Skills,Establishing and maintaining healthy relations...,Resolving conflicts constructively,Relationship Skills. Establishing and maintain...
12,Responsible Decision-Making,Making caring and constructive choices about p...,Identifying solutions to problems,Responsible Decision-Making. Making caring and...
13,Responsible Decision-Making,Making caring and constructive choices about p...,Analyzing information and facts,Responsible Decision-Making. Making caring and...
14,Responsible Decision-Making,Making caring and constructive choices about p...,Evaluating consequences of actions,Responsible Decision-Making. Making caring and...

In [ ]:
import pandas as pd

# Load preprocessed SEL knowledge
sel_df = pd.read_csv(
    "data/processed/sel_concepts_preprocessed.csv"
)

def sel_assistant(query):
    query = query.lower()

    # Find records containing words from the user's query
    matches = []

    for _, row in sel_df.iterrows():
        searchable_text = row["knowledge_text"].lower()

        if any(word in searchable_text for word in query.split()):
            matches.append(row)

    if len(matches) == 0:
        return """
I could not find a closely related SEL concept in my current
knowledge base.

Try asking about emotions, stress management, empathy,
communication, relationships, or decision-making.
"""

    # Use the first matching concept
    result = matches[0]

    response = f"""
SEL Assistant

Relevant SEL Competency:
{result['competency']}

Related Skill:
{result['skill']}

Explanation:
{result['description']}

This information is based on the CASEL SEL framework.
"""

    return response

In [18]:
question = "How can I manage stress?"

print(sel_assistant(question))

SEL Assistant

Relevant SEL Competency:
Self-Awareness

Related Skill:
Identifying emotions

Explanation:
Understanding one's own emotions, thoughts, values, strengths, and limitations.

This information is based on the CASEL SEL framework.

In [19]:
questions = [
    "How can I manage my emotions?",
    "How can I understand other people's feelings?",
    "How can I improve communication?",
    "How can I solve problems responsibly?"
]

for question in questions:
    print("=" * 60)
    print("USER:", question)
    print(sel_assistant(question))

============================================================
USER: How can I manage my emotions?

SEL Assistant

Relevant SEL Competency:
Self-Awareness

Related Skill:
Identifying emotions

Explanation:
Understanding one's own emotions, thoughts, values, strengths, and limitations.

This information is based on the CASEL SEL framework.

============================================================
USER: How can I understand other people's feelings?

SEL Assistant

Relevant SEL Competency:
Self-Awareness

Related Skill:
Identifying emotions

Explanation:
Understanding one's own emotions, thoughts, values, strengths, and limitations.

This information is based on the CASEL SEL framework.

============================================================
USER: How can I improve communication?

SEL Assistant

Relevant SEL Competency:
Self-Awareness

Related Skill:
Identifying emotions

Explanation:
Understanding one's own emotions, thoughts, values, strengths, and limitations.

This information is based on the CASEL SEL framework.

============================================================
USER: How can I solve problems responsibly?

SEL Assistant

Relevant SEL Competency:
Self-Awareness

Related Skill:
Identifying emotions

Explanation:
Understanding one's own emotions, thoughts, values, strengths, and limitations.

This information is based on the CASEL SEL framework.

In [20]:
print(sel_assistant)

<function sel_assistant at 0x7ecf8ce3fce0>

In [21]:
import inspect

print(inspect.getsource(sel_assistant))

def sel_assistant(query):
    query = query.lower()

    # Find records containing words from the user's query
    matches = []

    for _, row in sel_df.iterrows():
        searchable_text = row["knowledge_text"].lower()

        if any(word in searchable_text for word in query.split()):
            matches.append(row)

    if len(matches) == 0:
        return """
I could not find a closely related SEL concept in my current
knowledge base.

Try asking about emotions, stress management, empathy,
communication, relationships, or decision-making.
"""

    # Use the first matching concept
    result = matches[0]

    response = f"""
SEL Assistant

Relevant SEL Competency:
{result['competency']}

Related Skill:
{result['skill']}

Explanation:
{result['description']}

This information is based on the CASEL SEL framework.
"""

    return response

In [23]:
!pip -q install sentence-transformers

In [24]:
from sentence_transformers import SentenceTransformer

print("sentence-transformers installed successfully!")

sentence-transformers installed successfully!

In [25]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedding model loaded successfully!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully!

In [26]:
# Create embeddings for all SEL knowledge records

sel_embeddings = embedding_model.encode(
    sel_df["knowledge_text"].tolist(),
    normalize_embeddings=True
)

print("SEL embeddings created successfully!")
print("Number of records:", len(sel_embeddings))
print("Embedding size:", len(sel_embeddings[0]))

SEL embeddings created successfully!
Number of records: 15
Embedding size: 384

In [27]:
import numpy as np

def retrieve_sel(query, top_k=3):
    # Convert user question into an embedding
    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )[0]

    # Calculate similarity with all SEL records
    scores = np.dot(sel_embeddings, query_embedding)

    # Get the highest-scoring records
    top_indices = np.argsort(scores)[::-1][:top_k]

    results = sel_df.iloc[top_indices].copy()
    results["similarity_score"] = scores[top_indices]

    return results

In [28]:
results = retrieve_sel("How can I manage my emotions?", top_k=3)

results[[
    "competency",
    "skill",
    "similarity_score"
]]

        competency                                  skill  similarity_score
3  Self-Management                      Managing emotions          0.618865
4  Self-Management                        Managing stress          0.568462
5  Self-Management  Setting personal and collective goals          0.525223

In [29]:
test_questions = [
    "How can I manage my emotions?",
    "How can I understand other people's feelings?",
    "How can I improve communication?",
    "How can I solve problems responsibly?"
]

for question in test_questions:
    results = retrieve_sel(question, top_k=1)

    result = results.iloc[0]

    print("=" * 60)
    print("QUESTION:", question)
    print("COMPETENCY:", result["competency"])
    print("SKILL:", result["skill"])
    print("SIMILARITY:", round(result["similarity_score"], 3))

============================================================
QUESTION: How can I manage my emotions?
COMPETENCY: Self-Management
SKILL: Managing emotions
SIMILARITY: 0.619
============================================================
QUESTION: How can I understand other people's feelings?
COMPETENCY: Social Awareness
SKILL: Showing concern for others' feelings
SIMILARITY: 0.525
============================================================
QUESTION: How can I improve communication?
COMPETENCY: Relationship Skills
SKILL: Communicating effectively
SIMILARITY: 0.476
============================================================
QUESTION: How can I solve problems responsibly?
COMPETENCY: Responsible Decision-Making
SKILL: Identifying solutions to problems
SIMILARITY: 0.551